### ISSUE TITLE
absent function

### ISSUE THREAD

**Issue by CYRIL-7Z** [ndrplz/planar-distance-estimation#1]
hello, master~ I can't find draw_detections function in ssd_utils

**Comment by ndrplz** [comment]
Hi @ChauncyCai,
if you're looking for [this function](https://github.com/ndrplz/planar-distance-estimation/blob/90b32cc2dd8b961a71e42206cd0250cc958ae141/view_utils.py#L25-L84) you can find it in [`view_utils.py`](https://github.com/ndrplz/planar-distance-estimation/blob/90b32cc2dd8b961a71e42206cd0250cc958ae141/view_utils.py#L25-L84)
